Create Lrnr_glm_semiparametric
tlverse/sl3 pull request #357
Opened 2021-09-06 05:05 UTC by Larsvanderlaan

2021-09-06 18:41 UTC, Larsvanderlaan commented
Will add tests

2021-09-06 19:11 UTC, nhejazi commented
Hi @Larsvanderlaan --- thanks for this contribution, it'll be a nice addition to the package. I'll defer a more thorough review until the unit tests have been added, but, in the meantime, I wanted to note a few code style changes that should be implemented.

1. Over the past couple of months, we migrated the documentation style (via a PR merged into `devel`) to use markdown, include examples, and more closely adhere to a common structure. For an example, consider [`Lrnr_haldensify`](https://github.com/tlverse/sl3/blob/devel/R/Lrnr_haldensify.R). Please update the documentation for this contribution to match the new format. Although incomplete, work on this front is continuing in https://github.com/tlverse/sl3/pull/355 and will be necessary for CRAN submission.
2. As a matter of convention, either try to adhere to the [`tidyverse` style guide](https://style.tidyverse.org/) (e.g., `snake_case` variable and function names, `FALSE` instead of `F`, etc.), either manually or by running `make style` prior to requesting a review. This helps with enforcing a consistent style and improving code readability for reviewers.

2021-09-06 20:16 UTC, Larsvanderlaan commented
Hi @nhejazi, Thank you for the tips and references. I will document as is done in Lrnr_haldensify.

2021-09-10 18:28 UTC, nhejazi commented on R/Lrnr_glm_semiparametric
> +#' Semiparametric Generalized Linear Models
Please adhere to the [80-column rule](https://softwareengineering.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width) throughout, via manual or automatic line-breaking (you can enable this in RStudio, if that's the IDE you're using). `styler::style_pkg()` also enforces this automatically iirc.

2021-09-10 18:30 UTC, nhejazi commented on R/Lrnr_glm_semiparametric
> +#' and `f(W)` is a user-specified parametric function (e.g. `f(W) = model.matrix(formula_sp, W)`). The baseline function `E[Y|A=0,W]` is fit using a user-specified Learner (possibly pooled over value
I believe your package referenced a paper by Mark, Sherri, Susan for some of this methodology. If that's correct, please add this as a reference appropriately, including addition of the bibTeX entry into the `REFERENCES.bib` file in `inst/`; for how to cite, see, for example, https://github.com/tlverse/sl3/blob/devel/R/Lrnr_glmnet.R#L8.

2021-09-10 18:32 UTC, nhejazi commented on R/Lrnr_glm_semiparametric
> +#' }
Switch these to use the new markdown syntax that we're using in the `devel` branch. Again, `Lrnr_glmnet` gives a fine example for how to do this. Basically, you can get ride of all the LaTeX macros, like `\describe{}`, `\item{}`, etc. Also see the comment above about following the 80-column rule.

2021-09-10 18:33 UTC, nhejazi commented on R/Lrnr_glm_semiparametric
> +#' data <- data.table(W, A, Y_continuous, Y_binary, Y_count)
It's great to see so many examples. Note, however, that they need to all run in under 5sec (per CRAN policy), so consider wrapping some of them in `\dontrun{...}` blocks if the timing is cumulatively beyond the 5sec limit.

2021-09-10 18:33 UTC, nhejazi requested changes
Overall, this looks good. Please address the comments about documentation, styling, and examples.

2022-03-11 01:00 UTC, rachaelvp commented
Merged with current version of devel, updated documentation to adhere to 80-column rule, and replaced the ` symbols to denote code with `\code{}`. This learner is almost ready to be merged with devel. @Larsvanderlaan, we just need a test for the learner.

2022-03-11 20:35 UTC, rachaelvp commented
@Larsvanderlaan, could you please look over the documentation in `Lrnr_glm_semiparametric`, including the description of the learner and the arguments. I tried to generalize the functionality to prediction settings, so it's more inline with `sl3`. Also, `W` was never defined but used in notation. I assumed this denoted all covariates in the task, excluding the interaction variable. 

@nhejazi, examples require loading `glmnet` package. Do you think this is OK?

2022-03-12 18:27 UTC, nhejazi commented
if necessary, it's fine, but, if it's possible to rewrite the examples to just use `stats::glm` instead of `glment::glmnet` that would be better (to avoid adding `glmnet` as a hard dependency)

2022-03-16 01:27 UTC, Larsvanderlaan commented
@rachaelvp Thank you very much for doing this. The updated documentation looks great. Your interpretation of `W` is correct. I also removed the dependency with glmnet (which I hopefully did without making any new errors).

2022-03-27 23:59 UTC, merged

2022-03-28 15:52 UTC, nhejazi commented
Thanks @rachaelvp and @Larsvanderlaan for your work on this --- great to have this PR merged!